version: '2'
services:
  # admin:
  #   build:
  #     context: ./api
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   volumes:
  #     - ./admin
  # node:
  #   build: .
  #   ports:
  #     - 80:3000
  #   volumes:
  #     - ./:/code
  mongo:
    image: mongo:3.4.23
    volumes:
      - /tmp/mongo:/data/db
    ports:
      - "27017:27017"
