version: '3'
services:
   api:
     container_name: api
     image: latest123/foodshare-api
     restart: always
     build: .
     ports:
       - "7500:7500"
  mongo:
    image: mongo:3.4.23
    volumes:
      - /data/db
    ports:
      - "27017:27017"
